name: Continuous Deployment
on:
  push:
jobs:
  build:
    runs-on: [self-hosted, staging, linux, X64]
    environment: STAGING
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        # with:
        #   cmd: install # will run `yarn install` command
      # - name: Run build check
      #   run: npm run build
      - run: echo ${{secrets.NEXTJS_STAGING_ENV}}
      # - name: Install dependencies
      #   run: npm i
      # - name: Build
      #   run: yarn build
      # - name: Deploy
      #   uses: jakejarvis/s3-sync-action@v0.5.0
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.STAGING_AWS_S3_BUCKET }}
      #   env:
      #   CI: true
